version: '3'

services:
  api:
    image: vindow
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
    mongodb_data_container: