version: '3'

services:
  app:
    image: vindow
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
  mongo:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: vindow-be
      MONGODB_DATABASE: vindow-be-local
      MONGODB_PASS: vindowpw
    ports:
      - "3000:3000"